# Generated by Django 5.2.5 on 2025-09-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_customer_gender_alter_customer_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
