# Generated by Django 5.2.5 on 2025-08-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_department_manager_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
